package pl.jkuznik.utils.enums;

public enum MenuMessage {
    GREETINGS_MESSAGE,
    ERROR_MESSAGE,

    /** Main menu messages: */
    MAIN_MENU_MESSAGE,
    HARDWARE_MENU_MESSAGE,
    SOFTWARE_MENU_MESSAGE,
    LANGUE_MENU_MESSAGE,

    /** Hardware menu messages:*/
    ADD_COMPONENT_MESSAGE,

    /** Software menu messages: */
    ADD_FILE_MESSAGE,
    RUN_PROGRAM_MESSAGE,
    RUN_GAME_MESSAGE,
    END_GAME_MESSAGE,
    END_PROGRAM_MESSAGE,

    INPUT_FILE_NAME_MESSAGE,
    INPUT_FILE_SIZE_MESSAGE,
    INPUT_FILE_QUALITY_MESSAGE,
    INPUT_FILE_COMPRESSION_MESSAGE,
    INPUT_SONG_TITLE_MESSAGE,
    INPUT_SONG_BAND_NAME_MESSAGE,
    INPUT_FILE_NAME_FOR_DELETE_MESSAGE
}
